### ISSUE TITLE
Documentation and other questions...

### ISSUE THREAD

**Issue by Covvperwood** [rah-emil/angry-cart.js#1]
Thank u for a great work!!!
ur plugin is amazing, but there are not enough documentation 
i didn't found description of methods and due it i have to searching information by analyse of page source.
Moreover ur website is nonworking
https://cdn.rah-emil.ru/angry-cart.js/demo/#
I deem that a lot of people would be grateful if u did documentation like this one 
http://kenwheeler.github.io/slick/

P.S.
Thanks again and **good luck with ur project**!

**Comment by rah-emil** [comment]
Thanks for your feedback!
I will definitely do some normal documentation and more examples soon :)
